<?php

namespace AppBundle\Repository;

use AppBundle\Entity\CardToken;

/**
 * CardTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CardTokenRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string $customerEmail
     * @param string $cardNumber
     * @param string $cardToken
     * @throws \Doctrine\ORM\ORMException
     * @throws \Doctrine\ORM\OptimisticLockException
     */
    public function upsert(string $customerEmail, string $cardNumber, string $cardToken)
    {
        $token = $this->findOneBy([
            'customerEmail' => $customerEmail,
            'cardNumber' => $cardNumber,
            'token' => $cardToken
        ]);
        if (!$token) {
            $token = new CardToken();
            $token->setCustomerEmail($customerEmail);
            $token->setCardNumber($cardNumber);
            $this->getEntityManager()->persist($token);
        }
        if ($cardToken !== $token->getToken()) {
            $token->setToken($cardToken);
            $this->getEntityManager()->flush();
        }
    }
}
